name: "Test protect-branch-by-user"
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: yarn
      - run: yarn build
      - run: yarn test
