name: "Test protect-branch-by-user"
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          userId: yamatatsu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
